### ISSUE TITLE
TODO List for DP5

### ISSUE THREAD

**Issue by AnuarTB** [AnuarTB/atak-ui#1]
As Bootstrap is not directly compatible with React, I have imported library to our code, called [https://react-bootstrap.github.io/](url)

- [x] @temirrr Make beats scrollable. Make a playhead. (optional)
- [x] @kunduzb17 Implement help popovers: https://react-bootstrap.github.io/components/overlays/#popovers
- [x] @amanzholov8 Implement the functionality of a plus button. For now you can add only photos. https://react-bootstrap.github.io/components/modal/
- [x] @amanzholov8 Add player controls buttons to the navigation bar. (Play, Pause)
- [x] @anuartb Implement 'Edit Audio' interface. 
- [ ] @kunduzb17 (optional) Implement menu
- [x] @temirrr Add photo-adding function
- [ ] @amanzholov8 
- [ ] @AnuarTB typography

**Comment by temirrr** [comment]
First todo is done: 97c1593bc642db68e562aee489e6ab3fc8f46ea6

**Comment by amanzholov8** [comment]
4th is done:  c892663c6afe35c586affa1ac29ac0570d1b6706, 540b047433a5f699fa0bdd0b7b530640ab870cd6

**Comment by amanzholov8** [comment]
5th is done: 4fd15662cb3fa49bb94256c52c762dcfc70edfaf
